spring:
  profiles:
    active: local

management:
  server:
    port: 8080

  endpoint:
    health:
      enabled: true

  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /actuator
      exposure:
        include: "health"
