name: CD - Deploy to EC2

# 워크플로우 트리거 조건 설정
on:
  # main 브랜치에 Push 발생 시 실행
  push:
    branches: [ main ]

jobs:
  deploy-to-ec2:
    # 사용할 머신 환경 - 최신 Ubuntu LTS
    runs-on: ubuntu-latest
    # 사용할 환경(dev)의 Secrets와 Variables를 활성화
    environment: prod

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: Docker Buildx 설정 (멀티 플랫폼 빌드를 위해 사용)
        uses: docker/setup-buildx-action@v3

      - name: EC2 접속을 위한 SSH 키 설정
        run: |
          mkdir -p ~/.ssh                    # .ssh 디렉터리 생성
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2.pem  # 비밀키 파일 생성
          chmod 600 ~/.ssh/ec2.pem            # 비밀키 파일 권한 설정

      - name: JAR를 EC2로 복사
        run: |
          scp -i ~/.ssh/ec2.pem -o StrictHostKeyChecking=no build/libs/*.jar \
          ${{ secrets.EC2_HOST }}:/opt/api/api.jar

      - name: Restart systemd service on EC2
        run: |
          ssh -i ~/.ssh/ec2.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << EOF
            sudo systemctl restart api-test.service
          EOF