name: CI - Build

# 워크플로우가 실행될 트리거 조건 설정
on:
  # main 브랜치로 Pull Request 생성 또는 업데이트 시 실행
  pull_request:
    branches: [ main ]

  # main 브랜치로 직접 Push될 때도 실행
  push:
    branches: [ main ]

jobs:
  build:
    # 실행할 머신 환경 - 최신 Ubuntu LTS 버전 사용
    runs-on: ubuntu-latest # 확인 필요

    steps:
      - name: 소스 코드를 runner에 체크아웃
        uses: actions/checkout@v4 # 확인 필요

      - name: JDK 21 설치 및 설정 (corretto 배포판 사용)
        uses: actions/setup-java@v4 # 확인 필요
        with:
          distribution: 'corretto'     # 사용할 JDK 배포판
          java-version: '21'          # 설치할 JDK 버전

      - name: Gradle Wrapper 파일에 실행 권한 부여 (Linux 환경에서 필수)
        run: chmod +x ./gradlew

      - name: Gradle로 빌드 및 테스트 실행
        run: ./gradlew clean build --no-daemon -x test

      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@v3
        with:
            name: built-jar
            path: build/libs/*.jar